[package]
name = "CDCS"
version = "2.0.0-alpha-1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
openfile="2.0.0"
random_color = "0.5.1"
fltk = "1.1.11"